crypto directory moved to obj folder
fixes previous compilation error "crypto/hmac_sha256.cpp:34:1: fatal
error: opening dependency file obj/crypto/hmac_sha256.d: No such file or
directory"